DROP TABLE IF EXISTS `cv`;
CREATE TABLE `cv` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`user_id` int(11) NOT NULL,
	`overview` varchar(450) DEFAULT NULL,
	PRIMARY KEY (`id`),
    CONSTRAINT `FK_USER_01` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;